name: Release
on:
  push:
    branches:
      - main
      - beta
      - "*.x"
env:
  flutter_version: "2.2.3"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Build node12 template image
        run: |
          docker buildx build \
          --output type=image,push=false \
          --platform ${{ steps.buildx.outputs.platforms }} \
          --tag lenra/template-node12 \
          --build-args CI=true \
          template/node12
      - name: Build devtools-node12
        run: | 
          docker buildx build \
          --output type=image,push=false \
          --platform ${{ steps.buildx.ouputs.platforms }} \
          --tag lenra/devtools \
          --build-args CI=true \
          --build-args TEMPLATE_IMAGE=lenra/template-node12 \
          .
      - name: Setup node deps
        run: npm i conventional-changelog-conventionalcommits@4 @semantic-release/exec @semantic-release/git @semantic-release-plus/docker@2 -D
      - name: Release
        env:
          GTHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: npx semantic-release

